name: Ruby

on:
  push:
    branches: [ Alexandre#30 ]
  pull_request:
    branches: [ Alexandre#30 ]

jobs:
  test:

    runs-on: ubuntu 22.04.2

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.2'
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake