name: Continous Integration Ruby

on:
  push:
    branches: [ Alexandre#30 ]
  pull_request:
    branches: [ Alexandre#30 ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
          ruby-version: '3.2'
      - name: Install dependencies
        run: |
         gem install bundler
         bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rails test